ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'ILQR'
    NOISE_MULTIPLIER: 1.0
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2 # 2 x Agent Radius
  SENSORS: ['NOISY_POSE_SENSOR', 'POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    GOAL_FORMAT: POLAR
    DIMENSIONALITY: 2
  SUCCESS:
    SUCCESS_DISTANCE: 0.2 # 2 x Agent Radius
  GOAL_SENSOR_UUID: pointgoal
  MEASUREMENTS: ['DISTANCE_TO_GOAL', "SUCCESS", "SPL", "SOFT_SPL"]
DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz
