BASE_TASK_CONFIG_PATH: "configs/navigation/gibson_evaluate_noise_free.yaml"
TRAINER_NAME: "occant_nav"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
VIDEO_OPTION: [""]
TENSORBOARD_DIR: "tb/hierarchical_pseudo_pixel_gibson_6"
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/curiosity_extension/pixel_pseudo_gibson_6_v0_b128_sqrt/ckpt.25.pth"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "trained_models/occant/run_00/checkpoints"
T_MAX: 500

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: False

RL:
  ANS:
    goal_success_radius: 0.2 # 2 x agent radius
    planning_step: 0.25
    image_scale_hw: [128, 128]
    crop_map_for_planning: False
    MAPPER:
      map_size: 101
      registration_type: 'moving_average'
      thresh_entropy: 0.5
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      use_data_parallel: False
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'
      GP_ANTICIPATION:
        resnet_type: 'resnet18'
        unet_nsf: 16
    LOCAL_POLICY:
      use_heuristic_policy: True
      deterministic_flag: True

PRELOAD_MAP: False