ENVIRONMENT:
  MAX_EPISODE_STEPS: 10000
  ITERATOR_OPTIONS:
    SHUFFLE: False
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128
  DEPTH_SENSOR:
    WIDTH: 128
    HEIGHT: 128
TASK:
  TYPE: Exp-v0
  SENSORS: ['GT_POSE_SENSOR', 'GT_EGO_MAP', 'GT_EGO_WALL_MAP']
  GT_EGO_MAP:
    MAP_SIZE: 65
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [0.2, 1.5]
  GT_EGO_WALL_MAP:
    MAP_SIZE: 65
    MAP_SCALE: 0.05
    HEIGHT_THRESH: [1.0, 1.5]
  MEASUREMENTS: []
DATASET:
  TYPE: Exploration-v1
  SPLIT: val
  DATA_PATH: data/datasets/exploration/mp3d/v1/{split}/{split}.json.gz
