BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_train_w_ar.yaml"
TRAINER_NAME: "ppo_curiosity_hierarchical"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: ["tensorboard"]
TENSORBOARD_DIR: "tb/foi/curiosity"
VIDEO_DIR: "video_dir/foi/curiosity"
TEST_EPISODE_COUNT: 1
EVAL_CKPT_PATH_DIR: ""
NUM_PROCESSES: 2 # 40
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints/foi/curiosity"
PRELOAD_MAP: False
T_MAX: 500
T_EXP: 500
DISTRIBUTED: True

NUM_UPDATES: 5001
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 10

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 1 # 10
    global_reward_type: 'curiosity'
    global_reward_scale: 0.01
  ANS:
    use_ddp: True
    image_scale_hw: [128, 128]
    gpu_ids: [0]
    use_gt_positioning: False
    overall_map_size: 961 # gibson
#    overall_map_size: 2001 # mp3d
    obs_resized_dim: 84
    CURIOSITY:
      use_normalized_advantage: False
      curiosity_hidden_size: 512
      use_curiosity_rnn: False
      num_concat_obs: 4
      update_epochs: 1
    MAPPER:
      map_size: 101
      map_batch_size: 32
      replay_size: 10000 # very important otherwise it crasha
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      use_data_parallel: False
      gpu_ids: [0]
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'
      GP_ANTICIPATION:
        resnet_type: 'resnet18'
        unet_nsf: 16
    LOCAL_POLICY:
      use_heuristic_policy: False
