BASE_TASK_CONFIG_PATH: "configs/exploration/gibson_evaluate_noise_free.yaml"
TRAINER_NAME: "ppo_impact_hierarchical"
ENV_NAME: "ExpRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb/foi/grid/gibson_val"
VIDEO_DIR: "video_dir/foi/grid/gibson_val"
TEST_EPISODE_COUNT: 2000
EVAL_CKPT_PATH_DIR: "data/new_checkpoints/foi/grid/ckpt.25.pth"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
PRELOAD_MAP: False
T_MAX: 1000
T_EXP: 1000
SAVE_STATISTICS_FLAG: True

NUM_UPDATES: 10000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 100

EVAL:
  SPLIT: "val"
  USE_CKPT_CONFIG: True

RL:
  PPO:
    # ppo params
    ppo_epoch: 4
    num_mini_batch: 1
    global_reward_type: 'impact'
    global_reward_scale: 0.01
    num_global_steps: 4
  ANS:
    use_ddp: True
    image_scale_hw: [128, 128]
    use_gt_positioning: False
    overall_map_size: 961 # gibson
    visitation_count_divider: 5
    obs_resized_dim: 42
    CURIOSITY:
      use_normalized_advantage: False
      curiosity_hidden_size: 512
      use_curiosity_rnn: False
      num_concat_obs: 4
      update_epochs: 1
    MAPPER:
      map_size: 101
      map_batch_size: 32
      replay_size: 10000 # very important otherwise it crasha
      ignore_pose_estimator: False
      pose_predictor_inputs: ['ego_map']
      registration_type: 'moving_average'
      label_id: 'ego_map_gt_anticipated'
      use_data_parallel: False
      gpu_ids: []
    OCCUPANCY_ANTICIPATOR:
      type: 'occant_rgbd'

QUALITATIVE: False